name: Gitea Backup

on:
  schedule:
    - cron: "0 0 1 * *" # Runs at midnight on the first day of every month
  workflow_dispatch:

jobs:
  demo:
    name: Demo Job
    runs-on: ubuntu-24.04
    steps:
      - run: echo "hi"
