name: Gitea Backup

on:
  - workflow_dispatch

jobs:
  demo:
    name: Demo Job
    runs-on: ubuntu-24.04
    steps:
      - name: Send Telegram Message
        uses: ./.github/actions/tg-send-message
        with:
          message: "This is a demo message from the Gitea Backup workflow."
