name: Gitea Backup

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes
  workflow_dispatch:

jobs:
  demo:
    name: Demo Job
    runs-on: ubuntu-24.04
    steps:
      - run: curl -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TG_CHAT_ID }}&text=Test message"
